#!/usr/bin/env ruby

# This script starts a new Pry session with an instance and a config ready to
# go. You can create a new instance by running the create_appear_instance
# method at the default scope.

require "bundler/setup"
require "pry"
require "appear"
require "appear/editor"

def create_appear_instance
  config = Appear::Config.new
  config.silent = false
  instance = Appear::Instance.new(config)
  return [instance, config]
end

instance, config = create_appear_instance
services = instance.instance_variable_get('@all_services')
# nvim = Appear::Editor::Nvim.find_for_file(File.expand_path('.'))
# nvim = Appear::Editor::Nvim.new(Appear::Editor::Nvim.sockets.last, services)
nvim = Appear::Editor::Nvim.find_for_file(__FILE__, services)
ide = Appear::Editor::TmuxIde.new(services)
puts "generated instance = #{instance} from config = #{config}"
puts "connected nvim = #{nvim}"
puts "generated ide = #{ide}"

binding.pry
