#!/usr/bin/env ruby

# This script starts a new Pry session with an instance and a config ready to
# go. You can create a new instance by running the create_appear_instance
# method at the default scope.

require "bundler/setup"
require "pry"
require "appear"

def create_appear_instance
  config = Appear::Config.new
  config.silent = false
  instance = Appear::Instance.new(config)
  return [instance, config]
end

instance, config = create_appear_instance
puts "generated instance #{instance} from config #{config}"

binding.pry
